### PR TITLE
Fix redirect http to https

### LINKED ISSUE #120: [Enhancement]  Rewrite Plugin should rewrite http to https
Hello,
It would be cool, if vulcand could have a native way to redirect http to https.
Currently the rewrite plugin only allows to redirect a location/path to another.
It would be cool to have a Matcher that allows to match the complete URL and redirect to another like http://foo.bar to https://foo.bar or like http://foo.bar/admin/* to https://foor.bar

### PR DESCRIPTION
**Pull request by porjo**
Closes #120

### CODE REVIEW

**Comment by klizhentas** [comment]
Thanks! Can you add a test for it as well?

**Comment by porjo** [comment]
> Thanks! Can you add a test for it as well?

The test [TestRewriteScheme](https://github.com/mailgun/vulcand/blob/master/plugin/rewrite/rewrite_test.go#L236) was breaking after my change, however I'm not sure what it actually achieves, so I've commented it out for now.

**Comment by klizhentas** [comment]
I'll take a closer look tomorrow, thanks!

**Comment by klizhentas** [comment]
I've updated the test and merged it, thanks for helping with digging the TLS bug!

**Pull request closed without merging**
