### PR TITLE
Export SeverityFlag, so others can override it in the options struct.

### PR DESCRIPTION
**Pull request by pquerna**

### CODE REVIEW

**Comment by klizhentas** [comment]
Looks like CI is not hapy about it:

```
# github.com/mailgun/vulcand/service

service/options.go:50: s.s undefined (type *SeverityFlag has no field or method s)

service/options.go:59: s.s undefined (type *SeverityFlag has no field or method s)

service/options.go:64: s.s undefined (type *SeverityFlag has no field or method s)

service/service.go:72: s.options.LogSeverity.s undefined (type SeverityFlag has no field or method s)
```

**Comment by pquerna** [comment]
@klizhentas sorry did an edit in browser thing as i hit it, will re-submit with fixes in a bit.

**Comment by klizhentas** [comment]
no prob :) CI/CD ftw!

**Comment by pquerna** [comment]
@klizhentas better now, also incorps the changes in #233

**Comment by klizhentas** [comment]
thanks Sir!

**Pull request merged**
