### PR TITLE
Added ability to sync cluster with Etcd periodically.

### PR DESCRIPTION
**Pull request by archisgore**
The purpose of this change is to keep vulcand resilient against
long-running etcd clusters. This change allows vulcan to periodically
synchronize the latest members of the etcd cluster from the
member it is current connected to, this giving it fallback
members to use in case the primary member were to fail for
whatever reason.

This allows us to maintain the etcd cluster by adding new replacement machines,
and taking down older machines, but so long as the cluster itself
is running overall, vulcand instances talking to it, will continue to work.

### CODE REVIEW

**Comment by tboerger** [comment]
:+1:

**Comment by archisgore** [comment]
Ok hold on. I've broken some test. I can repro it locally. Wait for a fix. Working on it ASAP.

**Comment by mischief** [comment]
@archisgore there is a caveat to be aware of - if you point etcd client at a etcd proxy and call SyncCluster, your client url list will change to the upstream etcd servers, and not the proxy.

**Comment by mischief** [comment]
@archisgore also fyi, vulcand should probably switch to `github.com/coreos/etcd/client` at the earliest opportunity.

**Comment by archisgore** [comment]
Yup. That's precisely what I expect to happen.

**Comment by philips** [comment]
I would suggest that you sync cluster on some reasonable interval like 60s by default instead of disabling.

**Comment by tboerger** [comment]
And i think it should be disabled because of backwards compat.

**Comment by philips** [comment]
@tboerger fair enough

**Comment by archisgore** [comment]
Ok I figured out the cause of this UT failure. It's a race condition where, in some cases,

supervisor_test.go: TearDownTest() calls Supervisor.Stop() which closes s.restartC channel.

However, at around the same time, the engine.Subscribe() goroutine is sending a nil to the restartC channel which has already been closed.

**Comment by klizhentas** [comment]
@archisgore thanks for finding this race condidtion! can you add a separate issue about it, so we can address it?

**Pull request closed without merging**
